CREATE TABLE messages (
     id INT NOT NULL AUTO_INCREMENT,
     msg_text VARCHAR(140),
     msg_sent TINYINT(1) DEFAULT 0,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     created_at DATETIME NOT NULL DEFAULT 0,
     PRIMARY KEY (id) 
);